const initialData1 = [
  {
    name: "Albite, Sophia Joy",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Amara, Lobna",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Ansari, Zubair A",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Rivero, Natalie",
    phoneNumber: "561-401-6184",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },

  {
    name: "Aramayo-Lopez, Karla",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Botardo, Janelle",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Burdette, Shanise",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Carter, Nicole L",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Catledge-Torres, Tiffany",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Chellis, Christen",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Cressman, Tamara K",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Cunningham, Jason L",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Cyr, Jennifer",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Delgado, Angeliz",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Fox, Ryan R",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Gayle, Karu G",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Gonzalez, Cynthia",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Hallinan, Laura",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Han, Aileen",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Hogue, Diana M",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Kahan, Samantha",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Kim, Hyemin O",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Klein, Stephanie M",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Knudtson, Taylor",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Esonenjo, Charles I",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Krupa, Elizabeth A",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Larry, Alisa",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Larson, John",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Lewandowski, Franci Ann",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Madamba, Paul Renzie",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Manzo, Alexis G",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Meradieu, Nativa",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Miller, Makenzie L",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Ong, Linda N",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Perez, Katherine",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Ray, Jacqueline K",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Rios, Lisandra",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Sergi, Benisha L",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Shrikissoon, Devi B",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Singleton, Charlishia",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Siplin, Breona V",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Stine, Amanda",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Strachan, Indira",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Swales, Sydney",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Thermidor, Cherlie",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Tufino, Jacqueline",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Tuhy, Katharine B",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Upchurch, Anthony",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Weemes, Sophia",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: true,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Wilson, Cameron",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Yoakem, Sierra N",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Zaldivar, Yohana",
    phoneNumber: "xxx-xxx-xxxx",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
  {
    name: "Lamb, Margel",
    phoneNumber: "813-244-3638",
    lastFloated: "no floats logged",
    floating: false,
    dayShift: false,
    prevFloatDay: "no floats logged",
    selected: "09-21-2023",
    floatingTo: "",
    jobType: "RN",
  },
];

export default initialData1;
