const initialData1 = [
  {
    name: "Albite, Sophia Joy",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: false,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Almara, Lobna",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Ansari, Zubair A",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero",
    phoneNumber: "561-779-1572",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero5",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero6",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero7",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero8",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero9",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero10",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero11",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero12",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero13",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero14",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero15",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero16",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero17",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero18",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero19",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero20",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero21",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero22",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero23",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero24",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  {
    name: "Natalie Rivero25",
    phoneNumber: "123-456-7890",
    lastFloated: "no float yet",
    floating: false,
    dayShift: true,
    prevFloatDay: "no float yet",
    selected: "09-21-2023",
    floatingTo: "",
  },
  // Add more objects as needed
];

export default initialData1;
